version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/be-flask"
    schedule:
      interval: "weekly"
    
  - package-ecosystem: "github-actions" 
    directory: "/"
    schedule:
      interval: "monthly"